apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: drift
spec:
  name: wines-drift
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: seldonio/mlflowserver:1.14.0-dev
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 80
            failureThreshold: 200
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 80
            failureThreshold: 200
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
    graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: s3://mlflow/0/80b67d9daf6548e49b455bf075e8c0c6/artifacts/model
      envSecretRefName: seldon-init-container-secret
      logger:
        url: http://broker-ingress.knative-eventing.svc.cluster.local/wine/wine-inference-requests
        mode: request
      name: classifier
    name: wine-super-model
    replicas: 1
